version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  fastapi:
    build:
      context: ./backend  # Point to the backend directory
      dockerfile: Dockerfile  # Ensure this matches the name and location of your Dockerfile
    volumes:
      - ./backend/api_server:/app/api_server  # Mount the api_server directory
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  react:
    build:
      context: ./frontend  # Point to your frontend directory
      dockerfile: Dockerfile  # Ensure this matches the name and location of your Dockerfile
    ports:
      - "3000:3000"

volumes:
  postgres_data: